import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { getGlobalData } from "@/lib/wordpress";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { siteSettings, navMenus } = await getGlobalData();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header siteSettings={siteSettings} navMenus={navMenus} />
        {children}
        <Footer siteSettings={siteSettings} navMenus={navMenus} />
      </body>
    </html>
  );
}
